package com.swagger.demo.model;


import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

    @ApiModelProperty(notes = "Its Auto Generated By BackEnd")
    private String id;
    @ApiModelProperty(notes = "Employee Name")
    private String name;

}
